package com.khalawat.android.ui.theme

import androidx.compose.ui.graphics.Color

// --- Light Theme Colors ---
// Based on: dark mode design (sage/gold light + warm parchment)
val LightPrimary = Color(0xFF5d5f5b)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFFf5f5f0)
val LightOnPrimaryContainer = Color(0xFF6f706c)
val LightSecondary = Color(0xFF4d644d)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFcfeacc)
val LightOnSecondaryContainer = Color(0xFF536a53)
val LightTertiary = Color(0xFF735c00)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFfff4de)
val LightOnTertiaryContainer = Color(0xFF886c00)
val LightBackground = Color(0xFFfcf8f7)
val LightOnBackground = Color(0xFF1c1b1b)
val LightSurface = Color(0xFFfcf8f7)
val LightOnSurface = Color(0xFF1c1b1b)
val LightOnSurfaceVariant = Color(0xFF454843)
val LightSurfaceVariant = Color(0xFFe5e2e1)
val LightError = Color(0xFFba1a1a)
val LightOnError = Color(0xFFffffff)
val LightErrorContainer = Color(0xFFffdad6)
val LightOnErrorContainer = Color(0xFF93000a)
val LightOutline = Color(0xFF757873)
val LightOutlineVariant = Color(0xFFc5c7c1)

// --- Dark Theme Colors ---
// Based on: light mode design (shadow to light / dark theme)
val DarkPrimary = Color(0xFFf2ca50)
val DarkOnPrimary = Color(0xFF3c2f00)
val DarkPrimaryContainer = Color(0xFFd4af37)
val DarkOnPrimaryContainer = Color(0xFF554300)
val DarkSecondary = Color(0xFFb4cdb8)
val DarkOnSecondary = Color(0xFF203527)
val DarkSecondaryContainer = Color(0xFF364c3c)
val DarkOnSecondaryContainer = Color(0xFFa3bba7)
val DarkTertiary = Color(0xFFc6cee8)
val DarkOnTertiary = Color(0xFF283044)
val DarkTertiaryContainer = Color(0xFFabb2cc)
val DarkOnTertiaryContainer = Color(0xFF3d455a)
val DarkBackground = Color(0xFF131313)
val DarkOnBackground = Color(0xFFe5e2e1)
val DarkSurface = Color(0xFF131313)
val DarkOnSurface = Color(0xFFe5e2e1)
val DarkOnSurfaceVariant = Color(0xFFd0c5af)
val DarkSurfaceVariant = Color(0xFF353534)
val DarkError = Color(0xFFffb4ab)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000a)
val DarkOnErrorContainer = Color(0xFFffdad6)
val DarkOutline = Color(0xFF99907c)
val DarkOutlineVariant = Color(0xFF4d4635)
